# LDM Fine-tuning Configuration
# Training parameters
train_batch_size: 8
learning_rate: 5e-5
num_train_epochs: 30
max_train_steps: null # 10
gradient_accumulation_steps: 4
gradient_checkpointing: false

# Model parameters
pretrained_model_name_or_path: 'runwayml/stable-diffusion-v1-5'
modality: "t1ce"  # t1ce, t2, t1ce+t2
resolution: 512
mixed_precision: null

# Dataset parameters
max_train_samples: null # 2000

# Validation parameters
validation_steps: 1000
num_validation_samples: 6

# Logging parameters
logging_steps: 50
checkpointing_steps: 1000

# Optimization parameters
lr_scheduler: "cosine"        ####################### constant
lr_warmup_steps: 0            ####################### 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0

# Noise parameters
offset_noise: True

# Dilation parameters
dilation_size: 5
sigma: 5.0

# Inference parameters
guidance_scale: 7.5
num_inference_steps: 30
tumor_size: "medium-sized"  # small, mild, medium-sized, moderate, large

# Logging parameters
resume_from_checkpoint: null

# Environment
seed: 2025
dataloader_num_workers: 0

# Advanced settings
enable_xformers_memory_efficient_attention: false
allow_tf32: false
use_8bit_adam: false
